"""add token_usage to sessions

Revision ID: 0f2c360d63c6
Revises: cbe7b760aae2
Create Date: 2026-03-16 23:29:20.378199

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f2c360d63c6'
down_revision: Union[str, Sequence[str], None] = 'cbe7b760aae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token_usage', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'token_usage')
    # ### end Alembic commands ###
