"""add max_second_oven_racks to kitchen_configs

Revision ID: 1c8c1e18507a
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 00:28:38.266766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8c1e18507a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitchen_configs', sa.Column('max_second_oven_racks', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitchen_configs', 'max_second_oven_racks')
    # ### end Alembic commands ###
