"""add password_hash to user_profiles

Revision ID: 46264411096a
Revises: 0f2c360d63c6
Create Date: 2026-03-17 01:14:43.197887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46264411096a'
down_revision: Union[str, Sequence[str], None] = '0f2c360d63c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password_hash', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password_hash')
    # ### end Alembic commands ###
